package it.cambi.qrgui.db.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Temi18RouQue generated by hbm2java
 */
@Entity
@Table(name = "Temi18_ROU_QUE", schema = "EMIA")
public class Temi18RouQue implements java.io.Serializable
{

    private Temi18RouQueId id;
    private Temi15UteQue Temi15UteQue;
    private Temi17UteRou Temi17UteRou;

    public Temi18RouQue()
    {
    }

    public Temi18RouQue(Temi18RouQueId id, Temi15UteQue Temi15UteQue, Temi17UteRou Temi17UteRou)
    {
        this.id = id;
        this.Temi15UteQue = Temi15UteQue;
        this.Temi17UteRou = Temi17UteRou;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "rou", column = @Column(name = "C_ROU", nullable = false, precision = 10, scale = 0)),
            @AttributeOverride(name = "que", column = @Column(name = "C_QUE", nullable = false, precision = 10, scale = 0)),
            @AttributeOverride(name = "insQue", column = @Column(name = "D_INS_QUE", nullable = false, length = 7)),
            @AttributeOverride(name = "insRou", column = @Column(name = "D_INS_ROU", nullable = false, length = 7)) })
    public Temi18RouQueId getId()
    {
        return this.id;
    }

    public void setId(Temi18RouQueId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "C_QUE", referencedColumnName = "C_QUE", nullable = false, insertable = false, updatable = false),
            @JoinColumn(name = "D_INS_QUE", referencedColumnName = "D_INS_QUE", nullable = false, insertable = false, updatable = false) })
    public Temi15UteQue getTemi15UteQue()
    {
        return this.Temi15UteQue;
    }

    public void setTemi15UteQue(Temi15UteQue Temi15UteQue)
    {
        this.Temi15UteQue = Temi15UteQue;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "C_ROU", referencedColumnName = "C_ROU", nullable = false, insertable = false, updatable = false),
            @JoinColumn(name = "D_INS_ROU", referencedColumnName = "D_INS_ROU", nullable = false, insertable = false, updatable = false) })
    public Temi17UteRou getTemi17UteRou()
    {
        return this.Temi17UteRou;
    }

    public void setTemi17UteRou(Temi17UteRou Temi17UteRou)
    {
        this.Temi17UteRou = Temi17UteRou;
    }

}
