package it.cambi.qrgui.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/** Temi16QueCatAssId generated by hbm2java */
@Embeddable
public class Temi16QueCatAssId implements java.io.Serializable {

  private long que;
  private long cat;
  private Date insCat;
  private Date insQue;

  public Temi16QueCatAssId() {}

  public Temi16QueCatAssId(long que, long cat, Date insCat, Date insQue) {
    this.que = que;
    this.cat = cat;
    this.insCat = insCat;
    this.insQue = insQue;
  }

  @Column(name = "C_QUE", nullable = false, precision = 10, scale = 0)
  public long getQue() {
    return this.que;
  }

  public void setQue(long que) {
    this.que = que;
  }

  @Column(name = "C_CAT", nullable = false, precision = 10, scale = 0)
  public long getCat() {
    return this.cat;
  }

  public void setCat(long cat) {
    this.cat = cat;
  }

  @Column(name = "D_INS_CAT", nullable = false, length = 7)
  public Date getInsCat() {
    return this.insCat;
  }

  public void setInsCat(Date insCat) {
    this.insCat = insCat;
  }

  @Column(name = "D_INS_QUE", nullable = false, length = 7)
  public Date getInsQue() {
    return this.insQue;
  }

  public void setInsQue(Date insQue) {
    this.insQue = insQue;
  }

  public boolean equals(Object other) {
    if ((this == other)) return true;
    if ((other == null)) return false;
    if (!(other instanceof Temi16QueCatAssId)) return false;
    Temi16QueCatAssId castOther = (Temi16QueCatAssId) other;

    return (this.getQue() == castOther.getQue())
        && (this.getCat() == castOther.getCat())
        && ((this.getInsCat() == castOther.getInsCat())
            || (this.getInsCat() != null
                && castOther.getInsCat() != null
                && this.getInsCat().equals(castOther.getInsCat())))
        && ((this.getInsQue() == castOther.getInsQue())
            || (this.getInsQue() != null
                && castOther.getInsQue() != null
                && this.getInsQue().equals(castOther.getInsQue())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (int) this.getQue();
    result = 37 * result + (int) this.getCat();
    result = 37 * result + (getInsCat() == null ? 0 : this.getInsCat().hashCode());
    result = 37 * result + (getInsQue() == null ? 0 : this.getInsQue().hashCode());
    return result;
  }
}
