package it.cambi.qrgui.api.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/** Temi13DtbInf generated by hbm2java */
public class DtbInfDto implements java.io.Serializable {

  private DbInfId id;
  private Set<UteQueDto> Temi15UteQues = new HashSet<UteQueDto>(0);

  public DtbInfDto() {}

  public DtbInfDto(DbInfId id) {
    this.id = id;
  }

  public DtbInfDto(DbInfId id, Set<UteQueDto> Temi15UteQues) {
    this.id = id;
    this.Temi15UteQues = Temi15UteQues;
  }

  public DbInfId getId() {
    return this.id;
  }

  public void setId(DbInfId id) {
    this.id = id;
  }

  public Set<UteQueDto> getTemi15UteQues() {
    return this.Temi15UteQues;
  }

  public void setTemi15UteQues(Set<UteQueDto> Temi15UteQues) {
    this.Temi15UteQues = Temi15UteQues;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    DtbInfDto that = (DtbInfDto) o;
    return id.equals(that.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }
}
