package it.cambi.qrgui.services.db.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;
import java.util.Date;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * Temi15UteQueId generated by hbm2java
 */
@Embeddable
public class Temi15UteQueId implements java.io.Serializable
{

    private long que;
    private Date insQue;

    public Temi15UteQueId()
    {
    }

    public Temi15UteQueId(long que, Date insQue)
    {
        this.que = que;
        this.insQue = insQue;
    }
    
    @SequenceGenerator(name = "ttps15generator", sequenceName = "EMIA.SEMI15_ANA_QUE", allocationSize = 1)
    @GeneratedValue(strategy = SEQUENCE, generator = "ttps15generator")
    @Column(name = "C_QUE", nullable = false, precision = 10, scale = 0)
    public long getQue()
    {
        return this.que;
    }

    public void setQue(long que)
    {
        this.que = que;
    }

    @Column(name = "D_INS_QUE", nullable = false, length = 7)
    public Date getInsQue()
    {
        return this.insQue;
    }

    public void setInsQue(Date insQue)
    {
        this.insQue = insQue;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Temi15UteQueId))
            return false;
        Temi15UteQueId castOther = (Temi15UteQueId) other;

        return (this.getQue() == castOther.getQue())
                && ((this.getInsQue() == castOther.getInsQue())
                        || (this.getInsQue() != null && castOther.getInsQue() != null && this.getInsQue().equals(castOther.getInsQue())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getQue();
        result = 37 * result + (getInsQue() == null ? 0 : this.getInsQue().hashCode());
        return result;
    }

}
