package it.cambi.qrgui.services.db.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Temi17UteRou generated by hbm2java
 */
@Entity
@Table(name = "Temi17_UTE_ROU", schema = "EMIA")
public class Temi17UteRou implements java.io.Serializable
{

    private Temi17UteRouId id;
    private String des;
    private Set<Temi18RouQue> Temi18RouQues = new HashSet<Temi18RouQue>(0);

    public Temi17UteRou()
    {
    }

    public Temi17UteRou(Temi17UteRouId id, String des)
    {
        this.id = id;
        this.des = des;
    }

    public Temi17UteRou(Temi17UteRouId id, String des, Set<Temi18RouQue> Temi18RouQues)
    {
        this.id = id;
        this.des = des;
        this.Temi18RouQues = Temi18RouQues;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "rou", column = @Column(name = "C_ROU", nullable = false, precision = 10, scale = 0)),
            @AttributeOverride(name = "insRou", column = @Column(name = "D_INS_ROU", nullable = false, length = 7)) })
    public Temi17UteRouId getId()
    {
        return this.id;
    }

    public void setId(Temi17UteRouId id)
    {
        this.id = id;
    }

    @Column(name = "T_DES", nullable = false, length = 80)
    public String getDes()
    {
        return this.des;
    }

    public void setDes(String des)
    {
        this.des = des;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "temi17UteRou")
    public Set<Temi18RouQue> getTemi18RouQues()
    {
        return this.Temi18RouQues;
    }

    public void setTemi18RouQues(Set<Temi18RouQue> Temi18RouQues)
    {
        this.Temi18RouQues = Temi18RouQues;
    }

}
