package it.cambi.qrgui.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/** Temi15UteQueId generated by hbm2java */
public class Temi15UteQueId implements java.io.Serializable {

  private long que;
  private Date insQue;

  public Temi15UteQueId() {}

  public Temi15UteQueId(long que, Date insQue) {
    this.que = que;
    this.insQue = insQue;
  }

  public long getQue() {
    return this.que;
  }

  public void setQue(long que) {
    this.que = que;
  }

  public Date getInsQue() {
    return this.insQue;
  }

  public void setInsQue(Date insQue) {
    this.insQue = insQue;
  }

  public boolean equals(Object other) {
    if ((this == other)) return true;
    if ((other == null)) return false;
    if (!(other instanceof Temi15UteQueId)) return false;
    Temi15UteQueId castOther = (Temi15UteQueId) other;

    return (this.getQue() == castOther.getQue())
        && ((this.getInsQue() == castOther.getInsQue())
            || (this.getInsQue() != null
                && castOther.getInsQue() != null
                && this.getInsQue().equals(castOther.getInsQue())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (int) this.getQue();
    result = 37 * result + (getInsQue() == null ? 0 : this.getInsQue().hashCode());
    return result;
  }
}
