package it.cambi.qrgui.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final


import static jakarta.persistence.GenerationType.SEQUENCE;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/** Temi17UteRou generated by hbm2java */
@Entity
@Table(name = "Temi17_UTE_ROU", schema = "EMIA")
@IdClass(Temi17UteRouId.class)
public class Temi17UteRou implements java.io.Serializable {
  private String des;
  private Set<Temi18RouQue> Temi18RouQues = new HashSet<Temi18RouQue>(0);
  private long rou;
  private Date insRou;

  @SequenceGenerator(
      name = "ttps17generator",
      sequenceName = "EMIA.SEMI17_ANA_ROU",
      allocationSize = 1)
  @GeneratedValue(strategy = SEQUENCE, generator = "ttps17generator")
  @Column(name = "C_ROU", nullable = false, precision = 10, scale = 0)
  @Id
  public long getRou() {
    return this.rou;
  }

  public void setRou(long rou) {
    this.rou = rou;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "D_INS_ROU", nullable = false, length = 7)
  @Id
  public Date getInsRou() {
    return this.insRou;
  }

  public void setInsRou(Date insRou) {
    this.insRou = insRou;
  }

  public Temi17UteRou() {}

  public Temi17UteRou(long rou, Date insRou, String des) {
    this.rou = rou;
    this.insRou = insRou;
    this.des = des;
  }

  public Temi17UteRou(long rou, Date insRou, String des, Set<Temi18RouQue> Temi18RouQues) {
    this.rou = rou;
    this.insRou = insRou;
    this.des = des;
    this.Temi18RouQues = Temi18RouQues;
  }

  @Column(name = "T_DES", nullable = false, length = 80)
  public String getDes() {
    return this.des;
  }

  public void setDes(String des) {
    this.des = des;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "temi17UteRou")
  public Set<Temi18RouQue> getTemi18RouQues() {
    return this.Temi18RouQues;
  }

  public void setTemi18RouQues(Set<Temi18RouQue> Temi18RouQues) {
    this.Temi18RouQues = Temi18RouQues;
  }
}
