package it.cambi.qrgui.services.db.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Temi16QueCatAss generated by hbm2java
 */
@Entity
@Table(name = "Temi16_QUE_CAT_ASS", schema = "EMIA")
public class Temi16QueCatAss implements java.io.Serializable
{

    private Temi16QueCatAssId id;
    private Temi14UteCat Temi14UteCat;
    private Temi15UteQue Temi15UteQue;

    public Temi16QueCatAss()
    {
    }

    public Temi16QueCatAss(Temi16QueCatAssId id, Temi14UteCat Temi14UteCat, Temi15UteQue Temi15UteQue)
    {
        this.id = id;
        this.Temi14UteCat = Temi14UteCat;
        this.Temi15UteQue = Temi15UteQue;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "que", column = @Column(name = "C_QUE", nullable = false, precision = 10, scale = 0)),
            @AttributeOverride(name = "cat", column = @Column(name = "C_CAT", nullable = false, precision = 10, scale = 0)),
            @AttributeOverride(name = "insCat", column = @Column(name = "D_INS_CAT", nullable = false, length = 7)),
            @AttributeOverride(name = "insQue", column = @Column(name = "D_INS_QUE", nullable = false, length = 7)) })
    public Temi16QueCatAssId getId()
    {
        return this.id;
    }

    public void setId(Temi16QueCatAssId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "C_CAT", referencedColumnName = "C_CAT", nullable = false, insertable = false, updatable = false),
            @JoinColumn(name = "D_INS_CAT", referencedColumnName = "D_INS_CAT", nullable = false, insertable = false, updatable = false) })
    public Temi14UteCat getTemi14UteCat()
    {
        return this.Temi14UteCat;
    }

    public void setTemi14UteCat(Temi14UteCat Temi14UteCat)
    {
        this.Temi14UteCat = Temi14UteCat;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "C_QUE", referencedColumnName = "C_QUE", nullable = false, insertable = false, updatable = false),
            @JoinColumn(name = "D_INS_QUE", referencedColumnName = "D_INS_QUE", nullable = false, insertable = false, updatable = false) })
    public Temi15UteQue getTemi15UteQue()
    {
        return this.Temi15UteQue;
    }

    public void setTemi15UteQue(Temi15UteQue Temi15UteQue)
    {
        this.Temi15UteQue = Temi15UteQue;
    }

}
