package it.cambi.qrgui.services.db.model;
// Generated Apr 10, 2018 11:58:47 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Temi15UteQue generated by hbm2java
 */
@Entity
@Table(name = "Temi15_UTE_QUE", schema = "EMIA")
public class Temi15UteQue implements java.io.Serializable
{

    private Temi15UteQueId id;
    private Temi13DtbInf Temi13DtbInf;
    private String nam;
    private String json;
    private Set<Temi16QueCatAss> Temi16QueCatAsses = new HashSet<Temi16QueCatAss>(0);
    private Set<Temi18RouQue> Temi18RouQues = new HashSet<Temi18RouQue>(0);

    public Temi15UteQue()
    {
    }

    public Temi15UteQue(Temi15UteQueId id, String nam, String json)
    {
        this.id = id;
        this.nam = nam;
        this.json = json;
    }

    public Temi15UteQue(Temi15UteQueId id, Temi13DtbInf Temi13DtbInf, String nam, String json, Set<Temi16QueCatAss> Temi16QueCatAsses,
            Set<Temi18RouQue> Temi18RouQues)
    {
        this.id = id;
        this.Temi13DtbInf = Temi13DtbInf;
        this.nam = nam;
        this.json = json;
        this.Temi16QueCatAsses = Temi16QueCatAsses;
        this.Temi18RouQues = Temi18RouQues;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "que", column = @Column(name = "C_QUE", nullable = false, precision = 10, scale = 0)),
            @AttributeOverride(name = "insQue", column = @Column(name = "D_INS_QUE", nullable = false, length = 7)) })
    public Temi15UteQueId getId()
    {
        return this.id;
    }

    public void setId(Temi15UteQueId id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "C_TYP", referencedColumnName = "C_TYP"),
            @JoinColumn(name = "C_SCH", referencedColumnName = "C_SCH") })
    public Temi13DtbInf getTemi13DtbInf()
    {
        return this.Temi13DtbInf;
    }

    public void setTemi13DtbInf(Temi13DtbInf Temi13DtbInf)
    {
        this.Temi13DtbInf = Temi13DtbInf;
    }

    @Column(name = "T_NAM", nullable = false, length = 80)
    public String getNam()
    {
        return this.nam;
    }

    public void setNam(String nam)
    {
        this.nam = nam;
    }

    @Column(name = "T_JSON", nullable = false)
    public String getJson()
    {
        return this.json;
    }

    public void setJson(String json)
    {
        this.json = json;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "temi15UteQue")
    public Set<Temi16QueCatAss> getTemi16QueCatAsses()
    {
        return this.Temi16QueCatAsses;
    }

    public void setTemi16QueCatAsses(Set<Temi16QueCatAss> Temi16QueCatAsses)
    {
        this.Temi16QueCatAsses = Temi16QueCatAsses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "temi15UteQue")
    public Set<Temi18RouQue> getTemi18RouQues()
    {
        return this.Temi18RouQues;
    }

    public void setTemi18RouQues(Set<Temi18RouQue> Temi18RouQues)
    {
        this.Temi18RouQues = Temi18RouQues;
    }

}
